name: CI/CD

# Quando o workflow será executado
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest  # Ambiente Linux
    steps:
      # 1️⃣ Clonar o repositório
      - uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # 3️⃣ Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Rodar testes
      - name: Run tests
        run: |
          pytest -q
